stages:
  - deploy

variables:
  DEPLOY_SERVER: "your-server-ip-or-domain.com"  # Адрес сервера
  DEPLOY_USER: "deploy-user"                     # Пользователь для деплоя
  DEPLOY_PATH: "/var/www/your-project"           # Путь на сервере
  SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"             # Приватный ключ (должен быть в GitLab CI/CD Variables)

before_script:
  - apt-get update -qq && apt-get install -y -qq openssh-client rsync
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan "$DEPLOY_SERVER" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

deploy_production:
  stage: deploy
  only:
    - main  # или master, или нужная ветка
  script:
    - echo "Deploying to $DEPLOY_SERVER..."
    - rsync -avz --delete --exclude='.git' --exclude='.gitlab-ci.yml' ./ $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH && chmod -R 755 ."
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH && any-other-command-you-need"
  environment:
    name: production
    url: https://$DEPLOY_SERVER
