stages:
  - build
  - analyze
  - deploy

variables:
  IMAGE_NAME: my-docker-image:latest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

analyze:
  stage: analyze
  image: aquasec/dive:latest
  dependencies:
    - build
  script:
    - dive $IMAGE_NAME --ci
  allow_failure: false
  artifacts:
    when: always
  after_script:
    - echo "Анализ прошел успешно, можно переходить к деплою."

deploy:
  stage: deploy
  script:
    - echo "Запуск деплоя..."
  needs:
    - job: analyze
      artifacts: false
  rules:
    - if: $CI_JOB_STATUS == "success"
      when: always
